# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b1ecb436d5ca295a12b5d37872d1495edf91a6fff3490a2f9e6c10fa51c6e4b40f000d3d0d257d3f39ad454633920a6ff9ed6bf3b31fad132dd9e39325bd42

test:
  secret_key_base: d3d10df6d946f5b24fa2d56860c721f14e11d1a12bd0bd32b1d91ca2fef2183bb5b4fbc3abe623c973995b36d02aaa2bb3cd9205636992942f48ba8d639dcef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
